# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c4e5de90f27288d6e7a6b539c57c7ba53f6bd1e59b9f519ea16a70272490cfe9bea8305bfaeef7f2c5ac3946a4b36cef75cc66aeb01376742b3c7d9218f466e

test:
  secret_key_base: b3bb3fa59004c15520a9019063be329997a57ad3bb3fdb92f30929753906fdbfb47ad33dba16ece6158a79b5766f5a4809eef6ff156c8e58ca9787726833fd7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
